name: app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/login_background.jpeg
   - assets/social-media-google.png
   - assets/image1.jpg
   - assets/image2.jpg
   - assets/image3.jpg
